Repository emit-sds/SpecTf, pull requests merged in 2025-02, with the labels that each got.

#28 Readme update
  README.md
  spectf/README.md
  spectf_cloud/README.md
Labels: documentation

#31 COG output on spectf_cloud deploy
  .github/workflows/python-package.yml
  README.md
  pyproject.toml
  spectf_cloud/README.md
  spectf_cloud/deploy.py
Labels: enhancement

#43 Refactor the PyTorch Device Function
  spectf/utils.py
  spectf_cloud/comparison_models/ResNet/ResNet.py
  spectf_cloud/comparison_models/train_resnet.py
  spectf_cloud/comparison_models/training_utils/utils.py
  spectf_cloud/evaluation/eval_spectf.py
  spectf_cloud/train.py
Labels: enhancement

#34 Added Save Every Epoch CLI Option for Training SpecTf
  spectf_cloud/README.md
  spectf_cloud/train.py
Labels: enhancement

#39 Add Jupyter Example Doc
  .gitignore
  docs/example.ipynb
  spectf/utils.py
Labels: documentation

#48 added info about the spectf cloud dataset to the readme
  spectf_cloud/README.md
Labels: documentation

#49 Fixed Small Bug Where Train Wasn't Passing In GPU
  spectf/utils.py
  spectf_cloud/README.md
  spectf_cloud/train.py
Labels: bug

#47 SpecTf Cloud Arch Config and Util changes
  docs/example.ipynb
  spectf/dataset.py
  spectf/utils.py
  spectf_cloud/arch.yml
  spectf_cloud/deploy.py
  spectf_cloud/spectf_cloud_config.yml
  tests/test_utils.py
Labels: enhancement
